# Simplified YAML Schema for Speech & Debate Tournament Management
# This file will be converted to Atlas HCL format automatically

# Global settings
schema_name: main
rails_version: "8.0"

# Table definitions
tables:
  records:
    columns:
      id: primary_key
      user_id: integer -> users.id on_delete=cascade not_null
      record_type: string(100) not_null
      value: text
      created_at: datetime not_null
      updated_at: datetime not_null

  seasons:
    columns:
      id: primary_key
      name: string(100) not_null
      start_date: date not_null
      end_date: date not_null
      active: boolean default=false not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - active

  leagues:
    columns:
      id: primary_key
      name: string(255) not_null unique
      abbreviation: string(10)
      description: text
      website: string(500)
      contact_email: string(255)
      active: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null

  users:
    columns:
      id: primary_key
      first_name: string(100) not_null
      last_name: string(100) not_null
      email: string(255) not_null unique
      phone: string(20)
      school: string(255)
      graduation_year: integer
      league_id: integer -> leagues.id on_delete=set_null
      role: string(20) default='participant' not_null
      active: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - league_id
      - role

  teams:
    columns:
      id: primary_key
      name: string(255) not_null
      league_id: integer -> leagues.id on_delete=cascade not_null
      season_id: integer -> seasons.id on_delete=cascade not_null
      school: string(255)
      active: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - league_id
      - season_id

  team_memberships:
    columns:
      id: primary_key
      team_id: integer -> teams.id on_delete=cascade not_null
      user_id: integer -> users.id on_delete=cascade not_null
      role: string(50) default='member' not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - team_id
      - user_id
      - columns: [team_id, user_id]
        unique: true

  event_types:
    columns:
      id: primary_key
      name: string(100) not_null unique
      abbreviation: string(10)
      category: string(20) not_null # 'speech', 'debate', 'interpretation'
      participant_type: string(20) not_null # 'individual', 'team'
      max_participants_per_match: integer default=2 not_null
      description: text
      rules_url: string(500)
      active: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - category
      - participant_type

  tournaments:
    columns:
      id: primary_key
      name: string(255) not_null
      league_id: integer -> leagues.id on_delete=cascade not_null
      season_id: integer -> seasons.id on_delete=cascade not_null
      start_date: date not_null
      end_date: date not_null
      location: string(500)
      format: string(20) default='in_person' not_null # 'in_person', 'virtual', 'hybrid'
      registration_deadline: datetime
      max_participants: integer
      entry_fee: decimal(8,2)
      status: string(20) default='upcoming' not_null # 'upcoming', 'active', 'completed', 'cancelled'
      description: text
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - league_id
      - season_id
      - start_date
      - status

  tournament_events:
    columns:
      id: primary_key
      tournament_id: integer -> tournaments.id on_delete=cascade not_null
      event_type_id: integer -> event_types.id on_delete=cascade not_null
      max_participants: integer
      entry_fee: decimal(8,2)
      registration_deadline: datetime
      status: string(20) default='open' not_null # 'open', 'closed', 'cancelled'
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - tournament_id
      - event_type_id
      - columns: [tournament_id, event_type_id]
        unique: true

  rooms:
    columns:
      id: primary_key
      tournament_id: integer -> tournaments.id on_delete=cascade not_null
      name: string(100) not_null
      room_type: string(20) default='physical' not_null # 'physical', 'virtual'
      capacity: integer
      location: string(500)
      virtual_link: string(500)
      equipment: text
      notes: text
      available: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - tournament_id
      - room_type

  rounds:
    columns:
      id: primary_key
      tournament_event_id: integer -> tournament_events.id on_delete=cascade not_null
      round_number: integer not_null
      name: string(100) not_null
      round_type: string(20) default='preliminary' not_null # 'preliminary', 'elimination', 'final'
      start_time: datetime
      end_time: datetime
      status: string(20) default='scheduled' not_null # 'scheduled', 'active', 'completed', 'cancelled'
      notes: text
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - tournament_event_id
      - columns: [tournament_event_id, round_number]
        unique: true
      - start_time

  matches:
    columns:
      id: primary_key
      round_id: integer -> rounds.id on_delete=cascade not_null
      room_id: integer -> rooms.id on_delete=set_null
      match_number: integer not_null
      start_time: datetime
      end_time: datetime
      status: string(20) default='scheduled' not_null # 'scheduled', 'active', 'completed', 'cancelled'
      winner_id: integer
      winner_type: string(20) # 'User', 'Team'
      notes: text
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - round_id
      - room_id
      - columns: [round_id, match_number]
        unique: true
      - start_time

  match_participants:
    columns:
      id: primary_key
      match_id: integer -> matches.id on_delete=cascade not_null
      participant_id: integer not_null
      participant_type: string(20) not_null # 'User', 'Team'
      position: string(20) # 'affirmative', 'negative', 'speaker_1', etc.
      speaking_order: integer
      score: decimal(8,2)
      rank: integer
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - match_id
      - columns: [participant_id, participant_type]
      - columns: [match_id, participant_id, participant_type]
        unique: true

  judges:
    columns:
      id: primary_key
      user_id: integer -> users.id on_delete=cascade not_null
      tournament_id: integer -> tournaments.id on_delete=cascade not_null
      experience_level: string(20) default='novice' not_null # 'novice', 'experienced', 'expert'
      certifications: text
      preferences: text
      availability: text
      active: boolean default=true not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - user_id
      - tournament_id
      - columns: [user_id, tournament_id]
        unique: true

  match_judges:
    columns:
      id: primary_key
      match_id: integer -> matches.id on_delete=cascade not_null
      judge_id: integer -> judges.id on_delete=cascade not_null
      role: string(20) default='judge' not_null # 'judge', 'timekeeper', 'observer'
      status: string(20) default='assigned' not_null # 'assigned', 'confirmed', 'absent'
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - match_id
      - judge_id
      - columns: [match_id, judge_id]
        unique: true

  registrations:
    columns:
      id: primary_key
      tournament_event_id: integer -> tournament_events.id on_delete=cascade not_null
      participant_id: integer not_null
      participant_type: string(20) not_null # 'User', 'Team'
      registration_date: datetime not_null
      status: string(20) default='registered' not_null # 'registered', 'confirmed', 'withdrawn', 'disqualified'
      fee_paid: boolean default=false not_null
      payment_date: datetime
      notes: text
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - tournament_event_id
      - columns: [participant_id, participant_type]
      - columns: [tournament_event_id, participant_id, participant_type]
        unique: true
      - status

  awards:
    columns:
      id: primary_key
      name: string(255) not_null
      tournament_event_id: integer -> tournament_events.id on_delete=cascade not_null
      recipient_id: integer not_null
      recipient_type: string(20) not_null # 'User', 'Team'
      award_type: string(50) default='placement' not_null # 'placement', 'special', 'recognition'
      position: integer # 1st, 2nd, 3rd, etc.
      description: text
      awarded_at: datetime not_null
      created_at: datetime not_null
      updated_at: datetime not_null
    indexes:
      - tournament_event_id
      - columns: [recipient_id, recipient_type]
      - award_type
      - position

# Seed data definitions
seeds:
  event_types:
    - name: "Persuasive Speaking"
      abbreviation: "PERS"
      category: "speech"
      participant_type: "individual"
      max_participants_per_match: 8
      description: "A speech designed to convince the audience of a particular viewpoint"

    - name: "Informative Speaking"
      abbreviation: "INFO"
      category: "speech"
      participant_type: "individual"
      max_participants_per_match: 8
      description: "A speech that educates the audience about a specific topic"

    - name: "Original Oratory"
      abbreviation: "OO"
      category: "speech"
      participant_type: "individual"
      max_participants_per_match: 8
      description: "An original speech on a topic of the speaker's choosing"

    - name: "Duo Interpretation"
      abbreviation: "DUO"
      category: "interpretation"
      participant_type: "team"
      max_participants_per_match: 8
      description: "A dramatic performance by two people"

    - name: "Team Policy Debate"
      abbreviation: "TP"
      category: "debate"
      participant_type: "team"
      max_participants_per_match: 2
      description: "A debate format with two-person teams arguing policy resolutions"

    - name: "Lincoln Douglas Debate"
      abbreviation: "LD"
      category: "debate"
      participant_type: "individual"
      max_participants_per_match: 2
      description: "A one-on-one debate format focusing on value and philosophical arguments"

    - name: "Apologetics"
      abbreviation: "APOL"
      category: "speech"
      participant_type: "individual"
      max_participants_per_match: 8
      description: "A defense of the Christian faith in response to questions"
